var players = 
[
  {
    "POS": "1",
    "PLAYER": "Sergio Garcia",
    "TOPAR": "-9",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "71",
    "R2": "69",
    "R3": "70",
    "R4": "69",
    "TOT": "279"
  },
  {
    "POS": "2",
    "PLAYER": "Justin Rose",
    "TOPAR": "-9",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "71",
    "R2": "72",
    "R3": "67",
    "R4": "69",
    "TOT": "279"
  },
  {
    "POS": "3",
    "PLAYER": "Charl Schwartzel",
    "TOPAR": "-6",
    "TODAY": "-4",
    "THRU": "F",
    "R1": "74",
    "R2": "72",
    "R3": "68",
    "R4": "68",
    "TOT": "282"
  },
  {
    "POS": "T4",
    "PLAYER": "Thomas Pieters",
    "TOPAR": "-5",
    "TODAY": "-4",
    "THRU": "F",
    "R1": "72",
    "R2": "68",
    "R3": "75",
    "R4": "68",
    "TOT": "283"
  },
  {
    "POS": "T4",
    "PLAYER": "Matt Kuchar",
    "TOPAR": "-5",
    "TODAY": "-5",
    "THRU": "F",
    "R1": "72",
    "R2": "73",
    "R3": "71",
    "R4": "67",
    "TOT": "283"
  },
  {
    "POS": "6",
    "PLAYER": "Paul Casey",
    "TOPAR": "-4",
    "TODAY": "-4",
    "THRU": "F",
    "R1": "72",
    "R2": "75",
    "R3": "69",
    "R4": "68",
    "TOT": "284"
  },
  {
    "POS": "T7",
    "PLAYER": "Kevin Chappell",
    "TOPAR": "-3",
    "TODAY": "-4",
    "THRU": "F",
    "R1": "71",
    "R2": "76",
    "R3": "70",
    "R4": "68",
    "TOT": "285"
  },
  {
    "POS": "T7",
    "PLAYER": "Rory McIlroy",
    "TOPAR": "-3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "72",
    "R2": "73",
    "R3": "71",
    "R4": "69",
    "TOT": "285"
  },
  {
    "POS": "T9",
    "PLAYER": "Adam Scott",
    "TOPAR": "-2",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "75",
    "R2": "69",
    "R3": "69",
    "R4": "73",
    "TOT": "286"
  },
  {
    "POS": "T9",
    "PLAYER": "Ryan Moore",
    "TOPAR": "-2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "69",
    "R3": "69",
    "R4": "74",
    "TOT": "286"
  },
  {
    "POS": "T11",
    "PLAYER": "Russell Henley",
    "TOPAR": "-1",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "71",
    "R2": "76",
    "R3": "71",
    "R4": "69",
    "TOT": "287"
  },
  {
    "POS": "T11",
    "PLAYER": "Rickie Fowler",
    "TOPAR": "-1",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "73",
    "R2": "67",
    "R3": "71",
    "R4": "76",
    "TOT": "287"
  },
  {
    "POS": "T11",
    "PLAYER": "Hideki Matsuyama",
    "TOPAR": "-1",
    "TODAY": "-5",
    "THRU": "F",
    "R1": "76",
    "R2": "70",
    "R3": "74",
    "R4": "67",
    "TOT": "287"
  },
  {
    "POS": "T11",
    "PLAYER": "Brooks Koepka",
    "TOPAR": "-1",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "74",
    "R2": "73",
    "R3": "71",
    "R4": "69",
    "TOT": "287"
  },
  {
    "POS": "T11",
    "PLAYER": "Jordan Spieth",
    "TOPAR": "-1",
    "TODAY": "+3",
    "THRU": "F",
    "R1": "75",
    "R2": "69",
    "R3": "68",
    "R4": "75",
    "TOT": "287"
  },
  {
    "POS": "T16",
    "PLAYER": "Martin Kaymer",
    "TOPAR": "E",
    "TODAY": "-4",
    "THRU": "F",
    "R1": "78",
    "R2": "68",
    "R3": "74",
    "R4": "68",
    "TOT": "288"
  },
  {
    "POS": "T16",
    "PLAYER": "Steve Stricker",
    "TOPAR": "E",
    "TODAY": "-4",
    "THRU": "F",
    "R1": "75",
    "R2": "73",
    "R3": "72",
    "R4": "68",
    "TOT": "288"
  },
  {
    "POS": "T18",
    "PLAYER": "Fred Couples",
    "TOPAR": "+1",
    "TODAY": "E",
    "THRU": "F",
    "R1": "73",
    "R2": "70",
    "R3": "74",
    "R4": "72",
    "TOT": "289"
  },
  {
    "POS": "T18",
    "PLAYER": "Pat Perez",
    "TOPAR": "+1",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "74",
    "R2": "74",
    "R3": "70",
    "R4": "71",
    "TOT": "289"
  },
  {
    "POS": "T18",
    "PLAYER": "Lee Westwood",
    "TOPAR": "+1",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "70",
    "R2": "77",
    "R3": "68",
    "R4": "74",
    "TOT": "289"
  },
  {
    "POS": "T18",
    "PLAYER": "Jimmy Walker",
    "TOPAR": "+1",
    "TODAY": "E",
    "THRU": "F",
    "R1": "76",
    "R2": "71",
    "R3": "70",
    "R4": "72",
    "TOT": "289"
  },
  {
    "POS": "T22",
    "PLAYER": "Phil Mickelson",
    "TOPAR": "+2",
    "TODAY": "E",
    "THRU": "F",
    "R1": "71",
    "R2": "73",
    "R3": "74",
    "R4": "72",
    "TOT": "290"
  },
  {
    "POS": "T22",
    "PLAYER": "Jason Day",
    "TOPAR": "+2",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "74",
    "R2": "76",
    "R3": "69",
    "R4": "71",
    "TOT": "290"
  },
  {
    "POS": "T22",
    "PLAYER": "William McGirt",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "69",
    "R2": "73",
    "R3": "74",
    "R4": "74",
    "TOT": "290"
  },
  {
    "POS": "T22",
    "PLAYER": "Charley Hoffman",
    "TOPAR": "+2",
    "TODAY": "+6",
    "THRU": "F",
    "R1": "65",
    "R2": "75",
    "R3": "72",
    "R4": "78",
    "TOT": "290"
  },
  {
    "POS": "T22",
    "PLAYER": "Justin Thomas",
    "TOPAR": "+2",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "73",
    "R2": "76",
    "R3": "71",
    "R4": "70",
    "TOT": "290"
  },
  {
    "POS": "T27",
    "PLAYER": "Brendan Steele",
    "TOPAR": "+3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "74",
    "R2": "73",
    "R3": "75",
    "R4": "69",
    "TOT": "291"
  },
  {
    "POS": "T27",
    "PLAYER": "Daniel Berger",
    "TOPAR": "+3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "77",
    "R2": "73",
    "R3": "72",
    "R4": "69",
    "TOT": "291"
  },
  {
    "POS": "T27",
    "PLAYER": "Branden Grace",
    "TOPAR": "+3",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "76",
    "R2": "74",
    "R3": "71",
    "R4": "70",
    "TOT": "291"
  },
  {
    "POS": "T27",
    "PLAYER": "Brandt Snedeker",
    "TOPAR": "+3",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "75",
    "R2": "74",
    "R3": "69",
    "R4": "73",
    "TOT": "291"
  },
  {
    "POS": "T27",
    "PLAYER": "Jon Rahm",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "F",
    "R1": "73",
    "R2": "70",
    "R3": "73",
    "R4": "75",
    "TOT": "291"
  },
  {
    "POS": "32",
    "PLAYER": "Matthew Fitzpatrick",
    "TOPAR": "+4",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "71",
    "R2": "78",
    "R3": "73",
    "R4": "70",
    "TOT": "292"
  },
  {
    "POS": "T33",
    "PLAYER": "Francesco Molinari",
    "TOPAR": "+5",
    "TODAY": "E",
    "THRU": "F",
    "R1": "78",
    "R2": "72",
    "R3": "71",
    "R4": "72",
    "TOT": "293"
  },
  {
    "POS": "T33",
    "PLAYER": "Byeong Hun An",
    "TOPAR": "+5",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "76",
    "R2": "73",
    "R3": "74",
    "R4": "70",
    "TOT": "293"
  },
  {
    "POS": "T33",
    "PLAYER": "Jason Dufner",
    "TOPAR": "+5",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "71",
    "R2": "76",
    "R3": "70",
    "R4": "76",
    "TOT": "293"
  },
  {
    "POS": "T36",
    "PLAYER": "Brian Stuard",
    "TOPAR": "+6",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "77",
    "R2": "70",
    "R3": "74",
    "R4": "73",
    "TOT": "294"
  },
  {
    "POS": "T36",
    "PLAYER": "Stewart Hagestad",
    "TOPAR": "+6",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "74",
    "R2": "73",
    "R3": "74",
    "R4": "73",
    "TOT": "294"
  },
  {
    "POS": "T36",
    "PLAYER": "Soren Kjeldsen",
    "TOPAR": "+6",
    "TODAY": "+6",
    "THRU": "F",
    "R1": "72",
    "R2": "73",
    "R3": "71",
    "R4": "78",
    "TOT": "294"
  },
  {
    "POS": "T36",
    "PLAYER": "Adam Hadwin",
    "TOPAR": "+6",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "75",
    "R2": "74",
    "R3": "75",
    "R4": "70",
    "TOT": "294"
  },
  {
    "POS": "T36",
    "PLAYER": "Bill Haas",
    "TOPAR": "+6",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "75",
    "R2": "72",
    "R3": "71",
    "R4": "76",
    "TOT": "294"
  },
  {
    "POS": "T41",
    "PLAYER": "Louis Oosthuizen",
    "TOPAR": "+7",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "77",
    "R2": "71",
    "R3": "76",
    "R4": "71",
    "TOT": "295"
  },
  {
    "POS": "T41",
    "PLAYER": "Ross Fisher",
    "TOPAR": "+7",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "76",
    "R2": "74",
    "R3": "74",
    "R4": "71",
    "TOT": "295"
  },
  {
    "POS": "T43",
    "PLAYER": "Kevin Kisner",
    "TOPAR": "+8",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "74",
    "R2": "75",
    "R3": "74",
    "R4": "73",
    "TOT": "296"
  },
  {
    "POS": "T43",
    "PLAYER": "Bernd Wiesberger",
    "TOPAR": "+8",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "77",
    "R2": "72",
    "R3": "76",
    "R4": "71",
    "TOT": "296"
  },
  {
    "POS": "T43",
    "PLAYER": "Marc Leishman",
    "TOPAR": "+8",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "73",
    "R2": "74",
    "R3": "78",
    "R4": "71",
    "TOT": "296"
  },
  {
    "POS": "T46",
    "PLAYER": "Daniel Summerhays",
    "TOPAR": "+9",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "74",
    "R2": "75",
    "R3": "75",
    "R4": "73",
    "TOT": "297"
  },
  {
    "POS": "T46",
    "PLAYER": "Curtis Luck",
    "TOPAR": "+9",
    "TODAY": "E",
    "THRU": "F",
    "R1": "78",
    "R2": "72",
    "R3": "75",
    "R4": "72",
    "TOT": "297"
  },
  {
    "POS": "T48",
    "PLAYER": "Andy Sullivan",
    "TOPAR": "+10",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "71",
    "R2": "78",
    "R3": "76",
    "R4": "73",
    "TOT": "298"
  },
  {
    "POS": "T48",
    "PLAYER": "James Hahn",
    "TOPAR": "+10",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "75",
    "R2": "75",
    "R3": "75",
    "R4": "73",
    "TOT": "298"
  },
  {
    "POS": "50",
    "PLAYER": "J.B. Holmes",
    "TOPAR": "+11",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "78",
    "R2": "72",
    "R3": "73",
    "R4": "76",
    "TOT": "299"
  },
  {
    "POS": "51",
    "PLAYER": "Emiliano Grillo",
    "TOPAR": "+12",
    "TODAY": "+6",
    "THRU": "F",
    "R1": "79",
    "R2": "70",
    "R3": "73",
    "R4": "78",
    "TOT": "300"
  },
  {
    "POS": "52",
    "PLAYER": "Larry Mize",
    "TOPAR": "+17",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "74",
    "R2": "76",
    "R3": "79",
    "R4": "76",
    "TOT": "305"
  },
  {
    "POS": "53",
    "PLAYER": "Ernie Els",
    "TOPAR": "+20",
    "TODAY": "+6",
    "THRU": "F",
    "R1": "72",
    "R2": "75",
    "R3": "83",
    "R4": "78",
    "TOT": "308"
  },
  {
    "POS": "-",
    "PLAYER": "Billy Hurley III",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "75",
    "R2": "76",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Jim Furyk",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "78",
    "R2": "73",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Zach Johnson",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "77",
    "R2": "74",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Kevin Na",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "76",
    "R2": "75",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Danny Willett",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "73",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Chris Wood",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "74",
    "R2": "77",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Yuta Ikeda",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "74",
    "R2": "77",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Shane Lowry",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "72",
    "R2": "79",
    "R3": "--",
    "R4": "--",
    "TOT": "151"
  },
  {
    "POS": "-",
    "PLAYER": "Scott Piercy",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "73",
    "R2": "79",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Tommy Fleetwood",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "78",
    "R2": "74",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Russell Knox",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "76",
    "R2": "76",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Rafael Cabrera Bello",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "75",
    "R2": "77",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Rod Pampling",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "74",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Webb Simpson",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "75",
    "R2": "77",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Henrik Stenson",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "77",
    "R2": "75",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Alex Noren",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "74",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Bubba Watson",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "74",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "152"
  },
  {
    "POS": "-",
    "PLAYER": "Sean O&#39;Hair",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "76",
    "R2": "77",
    "R3": "--",
    "R4": "--",
    "TOT": "153"
  },
  {
    "POS": "-",
    "PLAYER": "Hudson Swafford",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "77",
    "R2": "76",
    "R3": "--",
    "R4": "--",
    "TOT": "153"
  },
  {
    "POS": "-",
    "PLAYER": "Brad Dalke",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "78",
    "R2": "75",
    "R3": "--",
    "R4": "--",
    "TOT": "153"
  },
  {
    "POS": "-",
    "PLAYER": "Jose Maria Olazabal",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "77",
    "R2": "76",
    "R3": "--",
    "R4": "--",
    "TOT": "153"
  },
  {
    "POS": "-",
    "PLAYER": "Vijay Singh",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "78",
    "R2": "75",
    "R3": "--",
    "R4": "--",
    "TOT": "153"
  },
  {
    "POS": "-",
    "PLAYER": "Bernhard Langer",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "75",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "153"
  },
  {
    "POS": "-",
    "PLAYER": "Patrick Reed",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "76",
    "R2": "77",
    "R3": "--",
    "R4": "--",
    "TOT": "153"
  },
  {
    "POS": "-",
    "PLAYER": "Jhonattan Vegas",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "78",
    "R2": "76",
    "R3": "--",
    "R4": "--",
    "TOT": "154"
  },
  {
    "POS": "-",
    "PLAYER": "Ian Woosnam",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "76",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "154"
  },
  {
    "POS": "-",
    "PLAYER": "Angel Cabrera",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "79",
    "R2": "75",
    "R3": "--",
    "R4": "--",
    "TOT": "154"
  },
  {
    "POS": "-",
    "PLAYER": "Trevor Immelman",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "79",
    "R2": "76",
    "R3": "--",
    "R4": "--",
    "TOT": "155"
  },
  {
    "POS": "-",
    "PLAYER": "Mike Weir",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "76",
    "R2": "79",
    "R3": "--",
    "R4": "--",
    "TOT": "155"
  },
  {
    "POS": "-",
    "PLAYER": "Gary Woodland",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "75",
    "R2": "80",
    "R3": "--",
    "R4": "--",
    "TOT": "155"
  },
  {
    "POS": "-",
    "PLAYER": "Jeunghun Wang",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "78",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "156"
  },
  {
    "POS": "-",
    "PLAYER": "Si Woo Kim",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "75",
    "R2": "81",
    "R3": "--",
    "R4": "--",
    "TOT": "156"
  },
  {
    "POS": "-",
    "PLAYER": "Mark O&#39;Meara",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "78",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "156"
  },
  {
    "POS": "-",
    "PLAYER": "Hideto Tanihara",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "76",
    "R2": "80",
    "R3": "--",
    "R4": "--",
    "TOT": "156"
  },
  {
    "POS": "-",
    "PLAYER": "Scott Gregory",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "82",
    "R2": "75",
    "R3": "--",
    "R4": "--",
    "TOT": "157"
  },
  {
    "POS": "-",
    "PLAYER": "Roberto Castro",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "79",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "157"
  },
  {
    "POS": "-",
    "PLAYER": "Tyrrell Hatton",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "80",
    "R2": "78",
    "R3": "--",
    "R4": "--",
    "TOT": "158"
  },
  {
    "POS": "-",
    "PLAYER": "Mackenzie Hughes",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "79",
    "R2": "80",
    "R3": "--",
    "R4": "--",
    "TOT": "159"
  },
  {
    "POS": "-",
    "PLAYER": "Sandy Lyle",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "77",
    "R2": "83",
    "R3": "--",
    "R4": "--",
    "TOT": "160"
  },
  {
    "POS": "-",
    "PLAYER": "Toto Gana",
    "TOPAR": "CUT",
    "TODAY": "-",
    "THRU": "CUT",
    "R1": "81",
    "R2": "80",
    "R3": "--",
    "R4": "--",
    "TOT": "161"
  },
  {
    "POS": "-",
    "PLAYER": "Dustin Johnson",
    "TOPAR": "DNS",
    "TODAY": "-",
    "THRU": "DNS",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  }
]
var players = 
var players = 
var players = 
var players = 
var players = 
var players = 
[
  {
    "POS": "1",
    "PLAYER": "Tony Finau",
    "TOPAR": "-4",
    "TODAY": "-4",
    "THRU": "17",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T2",
    "PLAYER": "Henrik Stenson",
    "TOPAR": "-3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "69",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "69"
  },
  {
    "POS": "T2",
    "PLAYER": "Charley Hoffman",
    "TOPAR": "-3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "69",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "69"
  },
  {
    "POS": "T2",
    "PLAYER": "Adam Hadwin",
    "TOPAR": "-3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "69",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "69"
  },
  {
    "POS": "T2",
    "PLAYER": "Patrick Reed",
    "TOPAR": "-3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "69",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "69"
  },
  {
    "POS": "T2",
    "PLAYER": "Li Haotong",
    "TOPAR": "-3",
    "TODAY": "-3",
    "THRU": "F",
    "R1": "69",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "69"
  },
  {
    "POS": "T2",
    "PLAYER": "Jordan Spieth",
    "TOPAR": "-3",
    "TODAY": "-3",
    "THRU": "13",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T8",
    "PLAYER": "Bernd Wiesberger",
    "TOPAR": "-2",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "70",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "70"
  },
  {
    "POS": "T8",
    "PLAYER": "Zach Johnson",
    "TOPAR": "-2",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "70",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "70"
  },
  {
    "POS": "T8",
    "PLAYER": "Marc Leishman",
    "TOPAR": "-2",
    "TODAY": "-2",
    "THRU": "F",
    "R1": "70",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "70"
  },
  {
    "POS": "T8",
    "PLAYER": "Rory McIlroy",
    "TOPAR": "-2",
    "TODAY": "-2",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T12",
    "PLAYER": "Vijay Singh",
    "TOPAR": "-1",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "71",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "71"
  },
  {
    "POS": "T12",
    "PLAYER": "Satoshi Kodaira",
    "TOPAR": "-1",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "71",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "71"
  },
  {
    "POS": "T12",
    "PLAYER": "Cameron Smith",
    "TOPAR": "-1",
    "TODAY": "-1",
    "THRU": "F",
    "R1": "71",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "71"
  },
  {
    "POS": "T12",
    "PLAYER": "Xander Schauffele",
    "TOPAR": "-1",
    "TODAY": "-1",
    "THRU": "15",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T12",
    "PLAYER": "Thomas Pieters",
    "TOPAR": "-1",
    "TODAY": "-1",
    "THRU": "15",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T12",
    "PLAYER": "Matt Kuchar",
    "TOPAR": "-1",
    "TODAY": "-1",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T12",
    "PLAYER": "Louis Oosthuizen",
    "TOPAR": "-1",
    "TODAY": "-1",
    "THRU": "13",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T19",
    "PLAYER": "Francesco Molinari",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "F",
    "R1": "72",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "72"
  },
  {
    "POS": "T19",
    "PLAYER": "Kyle Stanley",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "F",
    "R1": "72",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "72"
  },
  {
    "POS": "T19",
    "PLAYER": "Tommy Fleetwood",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "F",
    "R1": "72",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "72"
  },
  {
    "POS": "T19",
    "PLAYER": "Doug Ghim",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "F",
    "R1": "72",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "72"
  },
  {
    "POS": "T19",
    "PLAYER": "Fred Couples",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "F",
    "R1": "72",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "72"
  },
  {
    "POS": "T19",
    "PLAYER": "Russell Henley",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "17",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T19",
    "PLAYER": "Charl Schwartzel",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "16",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T19",
    "PLAYER": "Kevin Kisner",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "15",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T19",
    "PLAYER": "Phil Mickelson",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T19",
    "PLAYER": "Rafael Cabrera Bello",
    "TOPAR": "E",
    "TODAY": "E",
    "THRU": "12",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T29",
    "PLAYER": "Ted Potter Jr.",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Brian Harman",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Daniel Berger",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Pat Perez",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Jason Dufner",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Hideki Matsuyama",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Branden Grace",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Tiger Woods",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Bubba Watson",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Jimmy Walker",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "F",
    "R1": "73",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "73"
  },
  {
    "POS": "T29",
    "PLAYER": "Bernhard Langer",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "17",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T29",
    "PLAYER": "Yusaku Miyazato",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T29",
    "PLAYER": "Tyrrell Hatton",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T29",
    "PLAYER": "Rickie Fowler",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T29",
    "PLAYER": "Justin Rose",
    "TOPAR": "+1",
    "TODAY": "+1",
    "THRU": "12",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T44",
    "PLAYER": "Wesley Bryan",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Austin Cook",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Ryan Moore",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Jose Maria Olazabal",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Bryson DeChambeau",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Paul Casey",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Martin Kaymer",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Justin Thomas",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Sandy Lyle",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Ian Poulter",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "F",
    "R1": "74",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "74"
  },
  {
    "POS": "T44",
    "PLAYER": "Jon Rahm",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T44",
    "PLAYER": "Dustin Johnson",
    "TOPAR": "+2",
    "TODAY": "+2",
    "THRU": "12",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T56",
    "PLAYER": "Matthew Fitzpatrick",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "F",
    "R1": "75",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "75"
  },
  {
    "POS": "T56",
    "PLAYER": "Danny Willett",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "F",
    "R1": "75",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "75"
  },
  {
    "POS": "T56",
    "PLAYER": "Jason Day",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "F",
    "R1": "75",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "75"
  },
  {
    "POS": "T56",
    "PLAYER": "Si Woo Kim",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "F",
    "R1": "75",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "75"
  },
  {
    "POS": "T56",
    "PLAYER": "Patrick Cantlay",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "F",
    "R1": "75",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "75"
  },
  {
    "POS": "T56",
    "PLAYER": "Webb Simpson",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "16",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T56",
    "PLAYER": "Adam Scott",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T56",
    "PLAYER": "Alex Noren",
    "TOPAR": "+3",
    "TODAY": "+3",
    "THRU": "13",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T64",
    "PLAYER": "Brendan Steele",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Mike Weir",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Patton Kizzire",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Doc Redman",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Billy Horschel",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Chez Reavie",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Angel Cabrera",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Joaquin Niemann",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "F",
    "R1": "76",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "76"
  },
  {
    "POS": "T64",
    "PLAYER": "Shubhankar Sharma",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "17",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T64",
    "PLAYER": "Larry Mize",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "17",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T64",
    "PLAYER": "Yuta Ikeda",
    "TOPAR": "+4",
    "TODAY": "+4",
    "THRU": "17",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T75",
    "PLAYER": "Jhonattan Vegas",
    "TOPAR": "+5",
    "TODAY": "+5",
    "THRU": "F",
    "R1": "77",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "77"
  },
  {
    "POS": "T75",
    "PLAYER": "Kevin Chappell",
    "TOPAR": "+5",
    "TODAY": "+5",
    "THRU": "F",
    "R1": "77",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "77"
  },
  {
    "POS": "T75",
    "PLAYER": "Dylan Frittelli",
    "TOPAR": "+5",
    "TODAY": "+5",
    "THRU": "F",
    "R1": "77",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "77"
  },
  {
    "POS": "T78",
    "PLAYER": "Mark O&#39;Meara",
    "TOPAR": "+6",
    "TODAY": "+6",
    "THRU": "F",
    "R1": "78",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "78"
  },
  {
    "POS": "T78",
    "PLAYER": "Trevor Immelman",
    "TOPAR": "+6",
    "TODAY": "+6",
    "THRU": "F",
    "R1": "78",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "78"
  },
  {
    "POS": "T78",
    "PLAYER": "Ross Fisher",
    "TOPAR": "+6",
    "TODAY": "+6",
    "THRU": "F",
    "R1": "78",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "78"
  },
  {
    "POS": "T81",
    "PLAYER": "Ian Woosnam",
    "TOPAR": "+7",
    "TODAY": "+7",
    "THRU": "F",
    "R1": "79",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "79"
  },
  {
    "POS": "T81",
    "PLAYER": "Kiradech Aphibarnrat",
    "TOPAR": "+7",
    "TODAY": "+7",
    "THRU": "F",
    "R1": "79",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "79"
  },
  {
    "POS": "T81",
    "PLAYER": "Lin Yuxin",
    "TOPAR": "+7",
    "TODAY": "+7",
    "THRU": "16",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "84",
    "PLAYER": "Gary Woodland",
    "TOPAR": "+8",
    "TODAY": "+8",
    "THRU": "14",
    "R1": "--",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "--"
  },
  {
    "POS": "T85",
    "PLAYER": "Matt Parziale",
    "TOPAR": "+9",
    "TODAY": "+9",
    "THRU": "F",
    "R1": "81",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "81"
  },
  {
    "POS": "T85",
    "PLAYER": "Sergio Garcia",
    "TOPAR": "+9",
    "TODAY": "+9",
    "THRU": "F",
    "R1": "81",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "81"
  },
  {
    "POS": "87",
    "PLAYER": "Harry Ellis",
    "TOPAR": "+14",
    "TODAY": "+14",
    "THRU": "F",
    "R1": "86",
    "R2": "--",
    "R3": "--",
    "R4": "--",
    "TOT": "86"
  }
]
